### ISSUE TITLE
FFIECGeocMap Request

### ISSUE THREAD

**Issue by lodeddie** [rcash/ffiec_msilookup#3]
Hi, I tried to copy the same request you made to https://geomap.ffiec.gov/FFIECGeocMap/GeocodeMap1.aspx/GetGeocodeData 
with the form data object as sSingleLine and iCensusYear. However I am getting a 500 error. I am trying to replicate the call using postman as a post and header set to application/json. Let me know if this method still works
Thanks

**Comment by rcash** [comment]
@lodeddie The request still works, I have an internal tool using this method online currently.
